codecov

When using the script, I was seeing "Argument list too long" errors with the `curl` command, presumably because of the length of `$upload`.  Using `echo` to get the content of `$upload` and piping it into `curl` with `-d @-` to read data from the pipe works in the case where I had been getting the "Argument list too long" error.

Use echo and pipe to get upload data into curl

---

codecov

When setting $bower_components, the .bowerrc file was first read into
an environment variable, an this variable was then embedded in a
$(python -c "...") construct. This failed for my build due to newlines
in the .bowerrc file:
```
$ bash <(curl -s https://codecov.io/bash)
File "<string>", line 1
import json as j; print j.loads('{
^
SyntaxError: EOL while scanning string literal
```
We now simply let the Python JSON module read the .bowerrc file.

Handle newlines in .bowerrc

---

codecov

Prior to this change, using the -g option results the following bash error:
```
~/src/codecov-bash$ ./codecov -g test
Codecov v0.0.6
(url) https://codecov.io
==> No CI detected, using git for branch and commit sha.
==> find . -type f -name '*.gcno'
-not -path 'test' -exec gcov  {} +
bash: line 1: -not: command not found
```
This is because bash interprets an extraneous new-line character as a command terminator, and thus tries to execute a `-not ...` command.
This change simply removes the extraneous new-line character, resulting in the relevant `find` command being built correctly (at least for bash 4.3.30).
After this change, the above test is as follows:
```
~/src/codecov-bash$ ./codecov -g test
Codecov v0.0.6
(url) https://codecov.io
==> No CI detected, using git for branch and commit …
```

Correct the application of the -g option

---

codecov

Hello,
SCons generates and runs small C programs in the directory `.sconf_temp` to test for features (like Autoconf). When building with the `-coverage` option for GCC, these files are also built with this option, are run, and generate `.gcno` files. These are then found by the `codecov` Bash script, and skew your reports.
So I added the option `-g './scon*` to the command `bash <(curl -s https://codecov.io/bash)` in my Travis CI configuration file. But it would be nice to ignore these by default.

Ignore SCons temporary files

---

codecov
tests/test

slug changed for Bitrise
Bitrise won't generate `BITRISE_GIT_COMMIT` if the build was started manually

Bitrise CI support

---

codecov

Fixes the '-a' switch (extra arguments to pass to gcov), which is currently not working due to a variable name mixup.

Corrected gcov additional argument variable name.

---

codecov

Shippable provides Travis compatible environment variables: http://docs.shippable.com/ci_configure/#travis-compatible-variables
When detecting Travis, make sure the environment isn't Shippable.

Detect Shippable as such, instead of as Travis.

---

codecov

This fixes a mis-identification of a source file as coverage report and the search for reports in a out-of-source build (in a CMake based C++ project).
See also:
- https://github.com/gsauthof/libxfsx/commit/896cc0562116dd1b916f61152c769067a2065167
- https://github.com/gsauthof/libxfsx/commit/3f5fd67101439649a82743cb823b7ac13dd4df50
Both changes are tested in an older version of the script.

Fix out of source build

---

codecov

We really do not need file content in bash variable, it's better to just
get file size and then cat file directly to ouput.

Only count bytes in file instead of reading it into variable

---

codecov

- Removes double exclusion of .cmake
- Adds .bat and .ps1 to list

Improve find excludes

---

env

This commit ensures all parameters required by the python [1] and bash [2] uploader can easily be passed to a docker container [3]
[1] https://github.com/codecov/codecov-python/blob/7386c3c13fc71f237611c780646fa1b44a07dc64/codecov/__init__.py#L337
[2] https://github.com/codecov/codecov-bash/blob/441e2018ed76f4d8cb92dafa732ee24ebebb41f9/codecov#L429
[3] http://docs.codecov.io/docs/testing-with-docker#section-codecov-inside-docker

env: Ensure proper detection of CircleCI

---

codecov

This updates the script to use /usr/bin/env to locate bash, so in environments (such as FreeBSD) where it is not always in /bin/bash it won't fail (unless, of course, bash is not installed at all)

bash is not guaranteed to be in /bin/bash

---

codecov

The `-use-color` option must be passed _after_ the `show` command

Fix llvm-cov `-use-color` option

---

codecov

The argument to parse_yaml was passed as relative path to the repo root. When the script is run not from the repo root, the function is not able to find the config file.

Use full path to YAML file to parse it

---

codecov

It looks like there was a typo in a few places in the script (under the gitlab and teamcity services) where the variable `remove_addr` was being set instead of `remote_addr`.
@stevepeak

typo: remove_addr => remote_addr

---

codecov

With Xcode 9 `Coverage.profdata` resides in a different location. Look at the example.
/Users/distiller/Library/Developer/Xcode/DerivedData/Zewo-gcecuouhoxotyzgftixxatxncvem/Build/ProfileData/564D261E-47C4-4438-2AE3-56D166F5B432/Coverage.profdata
The change is compatible with Xcode 8 since it will just try to find it in a parent directory.

Fix build directory location due to Xcode 9 changes

---

codecov

When running in exported git repositories (for example) there will be no
"git_dir" present, so there should be a way to locate the .codecov.yml
file that doesn't depend on git.

Add -y option to specify a .codecov.yml file

---

codecov

```
bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/ea3bb59691fd907801f976f5f4e213b339296db3/codecov) -t [[REDACTED]] -F ifbyphone -n 'Ifbyphone Tests' -Z
```
```
find: paths must precede expression: ./vendor/asimlqt
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
```
```
_____          _
/ ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
\_____\___/ \__,_|\___|\___\___/ \_/
Bash-tbd
x> No CI provider detected.
Testing inside Docker? http://docs.codecov.io/docs/testing-with-docker
Testing with Tox? https://docs.codecov.io/docs/python#section-testing-with-tox
project root: .
Yaml not found, that's ok! Learn more at …
```

prevent vendor/* expansion 2

---

codecov

As the subject says, there is a missing backslash around line 1321.

Add missing backslash.

---

codecov

Follow-up to https://github.com/codecov/codecov-bash/commit/beaae435.

Fix handling of merge commit

---

codecov

If I am not mistaken (I am far from a Bash expert :-) ), the `$file` variable must be enclosed in quotes to ensure proper handling of spaces in the name. Otherwise each chunk of characters separated by a space are seen as a different argument by `basename`.
For example (a real case), if `$file` is not enclosed in quotes and its value is `./tests/karma-coverage/PhantomJS 2.1.1 (Linux 0.0.0)/lcov.info` the arguments received by `basename` would be `./tests/karma-coverage/PhantomJS`, `2.1.1`, `(Linux` and `0.0.0)/lcov.info` instead of a single one.

Enclose file name variable in quotes

---

codecov

Before: https://travis-ci.org/postgis/postgis/builds/348234119#L3566
After: https://travis-ci.org/postgis/postgis/builds/348433428#L5373
fixes upload of files of the same name in different pathes

Fix broken С paths upload

---

readme.md

* Update deployed link
* Remove CircleCI badge
* Update AppVeyor to Yes
* Update Bamboo to Yes
* Update Bitrise to Yes
* Add Teamcity
* Add Buddybuild
* Add Buildkite
* Add Heroku
* Add Azure Pipelines
* Remove Solano (dead site)
* Remove Magnum (invalid SSL cert)

Update readme.md with updated CI providers list

---

readme.md

The `sudo: false` option is now deprecated, see https://changelog.travis-ci.com/the-container-based-build-environment-is-fully-deprecated-84517.
This removes a reference to a deprecated Travis CI option.
N/A
No, as this is purely a documentation change.
N/A

Remove mention of Travis CI `sudo: false` in README

---

codecov

Previously, codecov failed if "TRAVIS_.*_VERSION" occurred anywhere in
the value of a multi-line environment variable. Make the value lookup
stricter by first filtering the names only, and only later resolve any
value for a matching key.
Fixes #133.

Make looking for a Travis language version variable stricter

---

codecov
tests/test

There is no env variable that links back to the build/job

Remove 'job' variable from Actions

---

env

Errors go into if, normal execution does not get indented

Straight execution in ./env

---

readme.md

re https://github.com/codecov/codecov-bash/pull/147#issuecomment-594236351 (@drazisil)
When opening a pull request from command line it is not immediately obvious that this needs to be done and looking into the .github/ folder is not something a lot of people would do either.

fix: docs for development

---

SHA1SUM
codecov
tests/test

What is the context of this pull request? Why is it being done?
This adds basic support for non-public GitHub Enterprise on AWS CodeBuild. We recently found that this didn't "just work" due to the slug being incorrectly determined. The uploader would make multiple attempts before failing with:
```
...
HTTP 400
slug must match pattern ^[\w\-\.\~\/]+\/[\w\-\.]{1,255}$
```
We noticed that in the upload request to our Codecov Enterprise server, the `slug` url param was the full repo url instead of the expected `org/repo` format (`&slug=https%3A%2F%2Fgit-instance.example.com%2Ffoo-org%2Fbar-repo&....`).
This should help a bit with codecov/codecov-bash#250.
Are there any changes that need to be called out as particularly tricky or significant?
This does remove the explicit domain matching that …

Update CodeBuild support for basic integration with GitHub Enterprise.

---

SHA1SUM
codecov

Changes to codecov uploading infrastructure mean the public-read header is no longer required. This PR removes the header.
Removal of `X-Amz-Acl: public-read`
https://github.com/codecov/codecov-bash/pull/302/commits/636a4221330da27a61db2d8474de9ede92fd8bd4

Remove public-read header

---

readme.md

This commit adds a specific commands for how to use the `codecov-bash` uploader on Alpine Linux.
Closes #361.

Improve the readme with Alpine Linux specifics

---

env

This is using the wrong env variable. Fixes https://github.com/codecov/codecov-bash/issues/370
No
None
N/A

Update env for GITHUB_ACTIONS

---

scripts/version.sh

Prevents deploys without a new tag. This will stop releases that may conflict with existing tagged versions.
No
No
N/A

fix: Prevent deploys if tag is not unique

---

readme.md

Announce the deprecation on the repository
None
N/A
N/A

docs: Add deprecation warning

---

scripts/version.sh

Your other packages e.g. https://github.com/codecov/codecov-circleci-orb rely on the assumption that published versions are versioned in github c.f. https://github.com/codecov/codecov-circleci-orb/issues/92 . However if a new version of codecov is added without the version string bumped, then you will publish the bash script but not version in github because not all errors in the version.sh script (without this change) are caught and passed out to CircleCI. 
Because of the way this change then interacts with the existing .circleci/config.yml script, errors on versioning will now be caught and prevent publishing if there is a problem, preventing this mismatch in future.
This will rely on the version string in the codecov script being updated when you want to release (which is required for …

fail if release fails. fixes #446
