codecov/codecov-bash

codecov

This looks like it works-- I recommend merge & deploy.

Newlines fix

---

codecov

* Make sure gcov is only called once
* Allow passing of args to gcov
* Allow configuration of gcov executable

Updates for more configurable gcov usage

---

codecov
tests/env-many.txt
tests/env.txt
tests/file.txt
tests/help.txt

> https://github.com/codecov/support/issues/43

Replace coveragepy to add <conditions>

---

codecov

This significantly reduces the load on Codecov servers by uploading directly to S3

Direct to s3 uploading

---

readme.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codecov/codecov-bash/20)

Correct minor grammatical mistakes

---

codecov

With many files the in memory concatenation is really slow, doing that
in file is much faster.
Issue #38 
Please note that this is untested code, so it might needs some adjustments!

Store upload data in temporary file rather than in memory

---

codecov

Appararently, these variables are available when you run your own Drone.
Source: http://readme.drone.io/usage/variables/

Support pr, job and tag with Drone

---

codecov

Fixes https://github.com/codecov/codecov-bash/issues/106.

Fix merge commit detection: only for PRs

---

codecov

Skip ending brackets in Dart files

---

ignores/results.txt
tests/test

Fix failing tests

---

readme.md

Add sha1sum to README

---

codecov
tests/test

Update codecov-bash repository with latest `master.sh` from codecov.io repository

Updated from latest codecov.io script

---

codecov
tests/test

Changed version to tbd

---

codecov
readme.md
tests/test

Support reporting from Cirrus CI

[CE-953] Support Cirrus CI

---

readme.md

Note that Azure Pipelines now supports tokenless upload
Nope
Doc-only change
Also make sure that you update the sha1 hash by running `sha1sum codecov` and updating the SHA1SUM file with the output
Change the `codecov` to `-` in the file before commiting so it can be compared against the server file

Azure Pipelines tokenless works

---

readme.md

Deployed Version is a link not an image

---

codecov
tests/test

Simple change to fix detection of AppVeyor on Linux.

Fixes detection of AppVeyor

---

SHA1SUM
codecov

a) Avoids a redirect
b) Promotes security!
No.
Non functional change.
✅

Make link in output be https

---

SHA1SUM
codecov

See https://github.com/codecov/codecov-bash/pull/265, this PR rebases it on master and adds the proper SHA1SUM. Since I don't have push access there I'm just opening a new PR to get this in :).
ping @jwillemsen and @drazisil

Use maxdepth as part of find #265 - 2

---

.gitignore
SHA1SUM
codecov

What is the context of this pull request? Why is it being done?
Remove leading period for codecov.yml
Are there any changes that need to be called out as particularly tricky or significant?: No
Is this covered by existing tests? New ones? If no, why not?: Yes
Done

Remove leading period for codecov.yml

---

.circleci/config.yml

Add fingerprints to deploy script
Nope
Nope
N/A

Add fingerprint

---

readme.md

Hello! I noticed that the table formatting seems to be broken so I thought I'd help out. If this isn't what you intended, you can go ahead and close this PR.

Minor Fix for README table formatting

---

.circleci/config.yml

Switching to use a new CircleCI context
None
None
N/A

Switch to use new CircleCI context

---

scripts/version.sh

fix comment into scripts/version.sh

---

readme.md

Update the docs for checksum verification based on best practices and from https://github.com/codecov/codecov-bash/pull/426
None
N/A
N/A

Update readme with verification steps
